import { ROLES, PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.STUDENTS,
    PERMISSIONS.ATTENDANCE,
    PERMISSIONS.FEES,
    PERMISSIONS.MANAGE_SALARY,
    PERMISSIONS.MANAGE_TEACHER,
    PERMISSIONS.MANAGE_FEE,
    PERMISSIONS.MANAGE_CLASS,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.STUDENTS,
    PERMISSIONS.ATTENDANCE,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.DASHBOARD,
    PERMISSIONS.FEES,
    PERMISSIONS.MANAGE_FEE,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.ATTENDANCE,
  ],
};
